---
collections:
  - name: git+https://github.com/QueraTeam/ansible-github.git
  - name: geerlingguy.mac

roles:
  - name: mariuskimmina.dotfiles
    src: https://github.com/mariuskimmina/ansible-role-dotfiles
