---
- name: common | update and upgrade packages (apt)
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
  when: ansible_pkg_mgr == 'apt'

- name: common | install packages (apt)
  package:
    name:
      - curl
      - fd-find
      - fzy
      - git
      - ripgrep
      - tmux
      - xclip
      - zip
      - zsh
    state: present
  when: ansible_os_family == 'Debian'

- name: common | install packages (brew)
  include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_installed_packages:
      - coreutils
      - curl
      - fd
      - fzy
      - git
      - ripgrep
      - tmux
      - zip
      - zsh
  when: ansible_os_family == 'Darwin'
