---
- name: fd | check if already linked
  stat:
    path: /usr/local/bin/nvim
  register: linked
  when: ansible_os_family == 'Debian'

- name: fd | get path to fdfind
  command: which fdfind
  register: fd_path
  when: not linked

- name: fd | get path to fdfind
  command: which fdfind
  register: fd_path
  when: not linked

- name: fd | symlink bin
  file:
    src: "{{ fd_path.stdout }}"
    dest: /usr/local/bin/fd
    state: link
  when: not linked
