---
# - name: nvim | install nvim dependencies (apt)
#   package:
#     name: []
#     state: present
#   when: ansible_os_family == 'Debian'

- name: nvim | check if nvim is already installed
  stat:
    path: /usr/local/bin/nvim
  register: installed

- name: nvim | download nvim
  quera.github.install_from_github:
    repo: neovim/neovim
    asset_regex: nvim-.*\.tar\.gz
    version_command: nvim --version
    move_rules:
      - src_regex: nvim-.*
        dst: /opt/nvim
        mode: 0755
  when: not installed.stat.exists

- name: nvim | symlink bin
  file:
    src: /opt/nvim/bin/nvim
    dest: /usr/local/bin/nvim
    state: link
