---
- name: starship | check if already installed
  stat:
    path: /usr/local/bin/starship
  register: installed

- name: starship | download installer
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship-installer.sh
    mode: "u+rwx"
  when: not installed.stat.exists
  register: download

- name: starship | run installer
  shell: /tmp/starship-installer.sh --yes
  when: download.changed

- name: starship | remove installer
  file:
    path: /tmp/starship-installer.sh
    state: absent
