---
- name: packages | update and upgrade packages (apt)
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_pkg_mgr == 'apt'
  become: true

- name: packages | install linuxbrew
  include_role:
    name: markosamuli.linuxbrew
  vars:
    linuxbrew_use_installer: true
    linuxbrew_init_shell: false
  when: ansible_os_family == 'Debian'

- name: packages | install brew
  include_role:
    name: geerlingguy.mac.homebrew
  when: ansible_os_family == 'Darwin'

- name: packages | install packages (brew)
  community.general.homebrew:
    name:
      - antidote
      - bazelisk
      - coreutils
      - curl
      - fd
      - fzy
      - git
      - go
      - ibazel
      - rustup-init
      - jq
      - krew
      - kubectl
      - neovim
      - node
      - pre-commit
      - python3
      - ripgrep
      - starship
      - stow
      - tmux
      - tpm
      - zip
      - zsh
    state: present
